insert into casa (nom) values ('Hufflepuff'), ('Gryffindor'), ('Ravenclaw'), ('Slytherin');

insert into profe (nom, casa_id) values
  ('Severus Snape', 4),
  ('Minerva McGonagall', 2),
  ('Filius Flitwick', 3),
  ('Pomona Sprout', 1),
  ('Remus Lupin', null),
  ('Aurora Sinistra', null),
  ('Rolanda Hooch', null),
  ('Charity Burbage', null),
  ('Cuthbert Binns', null),
  ('Albus Dumbledore', null);

insert into classes (materia, profe_id) values
  ('Pocions',
    (select id from profe where nom='Severus Snape')),
  ('Transfiguracio',
    (select id from profe where nom='Minerva McGonagall')),
  ('Encants',
    (select id from profe where nom='Filius Flitwick')),
  ('Herbologia',
    (select id from profe where nom='Pomona Sprout')),
  ('Defensa contra les arts oscures',
    (select id from profe where nom='Remus Lupin')),
  ('Astronomia',
    (select id from profe where nom='Aurora Sinistra')),
  ('Vol',
    (select id from profe where nom='Rolanda Hooch')),
  ('Estudis dels Muggle',
    (select id from profe where nom='Charity Burbage')),
  ('Historia de la Magia',
    (select id from profe where nom='Cuthbert Binns')),
  ('Director',
    (select id from profe where nom='Albus Dumbledore'));


insert into estudiant (nom, anyo, casa_id) values
  ('Waino Pouros', 7, 2),
  ('Daren Ortiz', 3, 4),
  ('Elbert Moore', 6, 2),
  ('Kaylee Grady', 4, 1),
  ('Elna Jacobs', 1, 2),
  ('Alisha Hartmann', 4, 2),
  ('Mya Dooley', 1, 4),
  ('Luigi Mante', 2, 4),
  ('Ella Stroman', 4, 2),
  ('Moses Prohaska', 5, 3),
  ('Ray Hermann', 7, 4),
  ('Sherman DuBuque', 2, 2),
  ('Sasha Volkman ', 6, 1),
  ('Ivah Kertzmann', 6, 1),
  ('Margret Blick', 2, 2),
  ('Marisol Armstrong', 4, 3),
  ('Holden Bahringer', 4, 3),
  ('Maximillia Brakus', 5, 4),
  ('Ashly Haley', 7, 4),
  ('Arnaldo Moore', 7, 1),
  ('Sarina Gottlieb', 5, 2),
  ('Brook Mraz', 5, 2),
  ('Mack Hills', 2, 2),
  ('Micaela DuBuque', 3, 1),
  ('Magnolia Schmidt', 7, 1),
  ('Kenneth Ryan', 4, 1),
  ('Alek Windler', 6, 2),
  ('Florian Feeney', 2, 4),
  ('Audie Hamill', 4, 3),
  ('Rhoda Jast', 5, 4),
  ('Lorena Wilderman', 1, 3),
  ('Dasia Roberts', 1, 2),
  ('Roy Runte', 1, 3),
  ('Matteo Feeney ', 6, 3),
  ('Electa Gislason', 7, 2),
  ('Natalie Russel', 4, 1),
  ('Oswaldo Daugherty', 6, 3),
  ('Fred Veum', 2, 3),
  ('Nels Thiel', 3, 2),
  ('Shawn Moen', 2, 3),
  ('Alfredo Hackett ', 1, 1),
  ('Arturo Nitzsche', 5, 2),
  ('Camille Stoltenberg', 5, 2),
  ('Ashlee Konopelski', 5, 3),
  ('Harmony Okuneva', 1, 2),
  ('Jacklyn Hilpert', 7, 2),
  ('Edward Mante', 7, 2),
  ('Orville Simonis', 1, 4),
  ('Antwon Johnson', 3, 2),
  ('Allie Schaefer', 5, 4),
  ('Zelda Schuster', 3, 3),
  ('Carleton Farrell', 2, 2),
  ('Ernesto Krajcik', 1, 1),
  ('Jason Marks', 4, 4),
  ('Elmer Swaniawski', 4, 4),
  ('Dawn Rosenbaum', 2, 4),
  ('Maryam Miller', 6, 1),
  ('Perry Konopelski', 4, 4),
  ('Jennie Raynor', 4, 3),
  ('Jermey Hills', 2, 1),
  ('Ari Klein', 6, 1),
  ('Alisa Brakus', 5, 4),
  ('Stephanie Bechtelar', 1, 1),
  ('Cornelius Daugherty ', 5, 2),
  ('Frieda Hayes', 4, 1),
  ('Angelina Hyatt', 2, 2),
  ('Cletus Hudson', 2, 3),
  ('Maxwell Parisian', 1, 3),
  ('Dario Blick', 4, 4),
  ('Camille Ryan ', 7, 3),
  ('Andy Reichert', 3, 2),
  ('Reid Romaguera', 5, 2),
  ('Nedra Russel', 3, 1),
  ('Lonny Quigley', 5, 3),
  ('Gerardo Grimes', 7, 1),
  ('Gaylord Mertz', 2, 1),
  ('Keira McDermott', 7, 3),
  ('Chadd Ledner', 1, 1),
  ('Earnestine Schulist', 2, 1),
  ('Scarlett Greenholt', 2, 1),
  ('Haylie Hintz ', 6, 3),
  ('Marion Rolfson', 5, 2),
  ('Shemar Rempel', 7, 3),
  ('Cristopher Ortiz', 5, 1),
  ('Aglae Nolan', 4, 2),
  ('Ellen Weissnat', 1, 1),
  ('Luther Smith', 3, 3),
  ('Vickie Feest ', 7, 3),
  ('Cheyenne Tillman', 4, 3),
  ('Carmine Friesen', 4, 2),
  ('Dee Morissette', 5, 2),
  ('Alvis Wuckert', 4, 2),
  ('Kayley Kling', 3, 1),
  ('Maeve Emard', 4, 1),
  ('Destin Roob', 6, 2),
  ('Morris Howe ', 3, 1),
  ('Cedrick Kuhn', 3, 1),
  ('Modesta Maggio', 3, 1),
  ('Edwardo Windler', 2, 3),
  ('Deshaun Collins', 3, 4),
  ('Rubie Mayert', 7, 2),
  ('Joseph Swift', 2, 4),
  ('Earnest Bernier', 7, 4),
  ('Meredith Herzog', 7, 1),
  ('Ambrose Reichert', 1, 1),
  ('Jerad Bailey', 3, 4),
  ('Alia Fadel', 1, 4),
  ('Mathilde Rosenbaum', 2, 1),
  ('Stephania Altenwerth', 4, 2),
  ('Nasir Runte', 7, 3),
  ('Conner Sawayn', 2, 3),
  ('Buster Beahan', 1, 2),
  ('Carlee Gorczany', 3, 4),
  ('Bettye Mosciski', 2, 1),
  ('Eugene Reinger', 1, 1),
  ('Breanna Bernhard', 1, 3),
  ('Davonte Pouros', 1, 3),
  ('Kay Luettgen', 6, 3),
  ('Zane Kerluke', 6, 1),
  ('Dawson Towne ', 3, 1),
  ('Lou Jacobi', 2, 3),
  ('Vena Friesen', 1, 3),
  ('Brett Tremblay', 2, 4),
  ('Gage Schinner', 7, 2),
  ('Kirk Lehner ', 4, 1),
  ('Corrine Sipes', 3, 4),
  ('Danyka Goodwin', 1, 3),
  ('Jack Kemmer ', 4, 4),
  ('Kyleigh Nader', 6, 3),
  ('Chauncey Mitchell', 2, 1),
  ('Eula Zboncak', 4, 4),
  ('Kathryn Schamberger', 1, 3),
  ('Alec Wisozk', 7, 1),
  ('Buddy Reynolds ', 7, 4),
  ('Fleta Schuster', 3, 1),
  ('Wava Ledner', 3, 4),
  ('Marian Bernier', 4, 3),
  ('Deja Block', 3, 4),
  ('Elmo Runte', 2, 1),
  ('Stephany Franecki', 7, 3),
  ('Dell Kuphal ', 1, 2),
  ('Verona OReilly', 3, 3),
  ('Ebony Bailey ', 6, 4),
  ('Dawn Cartwright', 1, 3),
  ('Edward Hegmann ', 1, 1),
  ('Dorthy Bartoletti', 3, 2),
  ('Macey Fisher', 1, 3),
  ('Lukas Gibson', 3, 1),
  ('Magdalen OHara', 3, 3),
  ('Stanley Reynolds', 4, 1),
  ('Rolando Gutkowski', 4, 2),
  ('Brice Rohan ', 4, 1),
  ('Darrion Gottlieb', 4, 1),
  ('Parker Ryan', 5, 2),
  ('Della Cruickshank', 6, 2),
  ('Scarlett Hodkiewicz', 5, 3),
  ('Finn Emard', 6, 3),
  ('Evert Upton', 4, 3),
  ('Bradly Koelpin', 7, 3),
  ('Brock Quitzon', 1, 2),
  ('Gladyce Champlin', 1, 2),
  ('Audrey Bednar', 4, 2),
  ('Vidal Marvin', 1, 3),
  (' Grady Osinski', 6, 2),
  ('Neha Zemlak', 2, 1),
  ('Ally Rau', 5, 1),
  ('Raina Kovacek', 4, 1),
  ('Irving Marquardt', 6, 2),
  ('Cordia Padberg', 6, 1),
  ('Stuart Predovic', 6, 1),
  ('Malinda Boyer', 3, 4),
  ('Germaine Kunde', 4, 4),
  ('Adrain Denesik', 5, 1),
  ('Kathryn Treutel', 1, 1),
  ('Gudrun Schowalter', 3, 1),
  ('Dedrick Jast', 4, 1),
  ('Rosina Kertzmann', 4, 4),
  ('Gideon Leannon', 1, 1),
  ('Adeline Wuckert', 1, 3),
  ('Felix Larkin', 5, 1),
  ('Chadd Lockman', 6, 2),
  ('Icie Koch', 5, 3),
  ('Claudia Wolf', 1, 4),
  ('Cindy Ullrich', 1, 2),
  ('Brycen Lueilwitz', 3, 3),
  ('Winnifred Macejkovic', 3, 1),
  ('Kallie Schmitt ', 3, 4),
  ('Noah Streich', 3, 2),
  ('Evans Kiehn', 1, 3),
  ('Sidney Kihn ', 2, 3),
  ('Fletcher Leannon', 2, 1),
  ('Carol Champlin', 2, 1),
  ('Adelle Dare', 3, 3),
  ('Otho Murazik', 1, 1),
  ('Viola VonRueden', 6, 4),
  ('Easton Gusikowski', 1, 3),
  ('Merlin Moore ', 7, 3),
  (' Kirsten Leffler', 2, 4),
  ('Janie Nienow', 1, 1),
  ('Seamus Kuvalis', 7, 2),
  ('Audreanne Harber', 1, 1),
  ('Ila Torphy', 3, 4),
  ('Marcelino Anderson', 4, 1),
  ('Boyd Ebert', 7, 1),
  ('Heaven Haley', 4, 1),
  ('Kaya Marquardt', 1, 4),
  ('Rodrigo Bogisich', 5, 3),
  ('Tiffany Schmidt', 5, 2),
  ('Isabelle Tromp', 1, 4),
  ('Annabel Considine', 6, 3),
  ('Carroll Waters', 6, 1),
  ('Aurelio Eichmann', 3, 2),
  ('Winnifred Hilll', 2, 3),
  ('Holly Fay', 1, 1),
  ('Burdette Herman', 2, 1),
  ('Calista Feeney', 4, 3),
  ('Dillon Green', 4, 4),
  ('Willy Dach', 5, 4),
  ('Gage Heller', 7, 2),
  ('Ryleigh Lakin', 4, 3),
  ('Ida Stokes', 3, 2),
  ('Roselyn Johnson ', 2, 1),
  ('Lea Franecki', 1, 1),
  ('Katherine Herman', 4, 1),
  ('Kendall Gerlach', 7, 1),
  ('Joshuah Collier', 6, 2),
  ('Edmond Swift', 7, 1),
  ('Savanah Reichert', 6, 2),
  ('Garnet Davis', 4, 4),
  ('Efren Cassin', 5, 4),
  ('Kip Jacobs', 2, 2),
  ('Michale Collins', 4, 1),
  ('Harley Hammes', 3, 1),
  ('Gerry Wilkinson', 2, 3),
  ('Tyrique Ullrich', 3, 1),
  ('Kellie Herzog', 5, 3),
  ('Santina Roob ', 4, 1),
  ('Garrison Doyle', 1, 4),
  ('Malachi Bartell', 5, 3),
  ('Rossie Schaefer', 2, 3),
  ('Ewald Beer', 3, 4),
  ('Arjun Hegmann', 5, 1),
  ('Green Kunde', 2, 4),
  ('Delia Kuphal ', 3, 1),
  ('Florida Hamill', 7, 4),
  ('Stephania Franecki', 5, 1),
  ('Renee Conn', 7, 4),
  ('Eusebio Lockman', 4, 4),
  ('Lauriane Sipes', 6, 2),
  ('Sabrina Hagenes', 3, 4),
  ('Rosendo Schaden ', 4, 3),
  ('Kaci Klocko ', 5, 3),
  ('Iliana Will', 6, 4),
  ('Aurelie Boyle', 4, 3),
  ('Taurean Satterfield', 1, 2),
  ('Liam Kris ', 4, 3),
  ('Reagan Kris', 4, 3),
  ('Athena Fritsch', 1, 3),
  ('Jena Johns', 6, 3),
  ('Nolan Little', 3, 4),
  ('Elisabeth Lehner', 2, 4),
  ('Gaetano Simonis', 7, 2),
  ('Claire Bode', 1, 1),
  ('Elliot Witting', 3, 1),
  ('Lois Beer', 5, 1),
  ('Shanelle Willms', 1, 4),
  ('Dovie Cartwright', 2, 3),
  ('Kurtis Hermann', 2, 2),
  ('Floyd Schuppe', 5, 3),
  ('Matt Wehner', 3, 4),
  ('Danielle Dickinson', 6, 3),
  ('Mariana Cormier ', 5, 2),
  ('Nadia Hoeger', 1, 2),
  ('Verla Reynolds', 4, 2),
  ('Sylvester Skiles', 5, 2),
  ('Susie Bosco', 5, 1),
  ('Delaney Leannon', 7, 4),
  ('Ansel Rice', 5, 4),
  ('Abdul Mitchell', 6, 1),
  ('Landen Zulauf', 6, 3);
